services:
  discovery-service:
    container_name: discovery-service
    build: ./discovery_service
    ports:
      - 8761:8761

  user-service:
    container_name: user-service
    build: ./user_service
    env_file: .env
    depends_on:
      - discovery-service
      - user-service-db
    ports:
      - 8081:8081

  user-service-db:
    container_name: user-service-db
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=${USER_DB_POSTGRES_DB_NAME}
      - POSTGRES_PASSWORD=${USER_DB_POSTGRES_PASSWORD}
      - POSTGRES_USER=${USER_DB_POSTGRES_USER}
    ports:
      - 5432:5432
    volumes:
      - user-db-data:/var/lib/postgresql/data

  book-service:
    container_name: book-service
    build: ./book_service
    env_file: .env
    depends_on:
      - discovery-service
      - book-service-db
    ports:
      - 8082:8082

  book-service-db:
    container_name: book-service-db
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=${BOOK_DB_POSTGRES_DB_NAME}
      - POSTGRES_USER=${BOOK_DB_POSTGRES_USER}
      - POSTGRES_PASSWORD=${BOOK_DB_POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - book-db-data:/var/lib/postgresql/data

  review-service:
    container_name: review-service
    build: ./review_service
    env_file: .env
    depends_on:
      - discovery-service
      - review-service-db
    ports:
      - 8083:8083

  review-service-db:
    container_name: review-service-db
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=${REVIEW_DB_POSTGRES_DB_NAME}
      - POSTGRES_USER=${REVIEW_DB_POSTGRES_USER}
      - POSTGRES_PASSWORD=${REVIEW_DB_POSTGRES_PASSWORD}
    ports:
      - 5434:5432
    volumes:
      - review-db-data:/var/lib/postgresql/data

  api-gateway:
    container_name: api-gateway
    build: ./api_gateway
    env_file: .env
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
    depends_on:
      - discovery-service
      - user-service
      - book-service
      - review-service
    ports:
      - 8080:8080

volumes:
  user-db-data:
  book-db-data:
  review-db-data:
